### PR TITLE
[MCH-112-26] chore: deploy stalth vault with flexible eoa-gas control

### PR DESCRIPTION
**Pull request by skeletor-spaceman**

### CODE REVIEW

**Review by b0dhidharma — APPROVED** [review]
@skeletor-spaceman action checking lint on commits is failing because of [MCH] -- is there a way of chaging it to be something like chore(MCH-112-26) ? as an example.

**Comment by skeletor-spaceman** [comment]
> @skeletor-spaceman action checking lint on commits is failing because of [MCH] -- is there a way of chaging it to be something like chore(MCH-112-26) ? as an example.

Now it seems to be all green, right?

**Comment by b0dhidharma** [comment]
> > @skeletor-spaceman action checking lint on commits is failing because of [MCH] -- is there a way of chaging it to be something like chore(MCH-112-26) ? as an example.
> 
> Now it seems to be all green, right?

not really. got to check CI. For some reason it works in the PR, but look at "main" last commit failed 😢

**Comment by skeletor-spaceman** [comment]
@b0dhidharma  Ouch, sorry that was my bad, let's amend and force push

**Pull request merged**
